package viewmodel;

import java.util.Date;
import java.util.List;

public class RequestInfoVM {

	public Long id;
	public String trim;
	public String month;
	public String vin;
	public String model;
	public String message;
	public String firstName;
	public String lastName;
	public long timeDiff;
	public String make;
	public String year;
	public String type;
	public String last4Vin;
	public String mileage;
	public String diffDays;
	public String leadTypeForNotif;
	public String typeofVehicle;
	public Integer price;
	public int notifFlag;
	public String stock;
	public String  declineReason;
	public String imagePath;
	public String mesg;
	public String bodyStyle;
	public String engine;
	public String transmission;
	public String drivetrain;
	public String imgId;
	public String name;
	public String hostName;
	public String email;
	public String phone;
	public String timeUnit;
	public String requestDate;
	public String bestDay;
	public String bestTime;
	public String confirmDate;
	public Date confirmDateOrderBy;
	public String confirmEndTime;
	public String confirmTime;
	public boolean isRead;
	public boolean is_google;
	public List<NoteVM> note;
	public Integer noteFlag;
	public String status;
	public String notes;
	public String action;
	public String statusDate;
	public String salesRep;
	public String prefferedContact;
	public String leadType;
	public String howContactedUs;
	public String howFoundUs;
	public String typeOfLead;
	public int option;
	public String isgoogle;
	public String enthicity;
	public String custZipCode;
	public String pdfPath;
	public LeadVM leadsValue;
	public String meeting;
	public String userRole;
	public String meetingStatus;
	public String testDriveCompletedComment;
	public String testDriveCompletedDuration;
	public List<RequestInfoVM> parentChildLead;
	public Boolean is_google_data;
	public String google_id;
	public Long groupId;
	public Integer setFlagSameUser;
	public List<UserVM> userdata;
	public String imageUrl;
	public String reason;
	public String weatherValue;
	public String cnfDateNature;
	public Integer premiumFlag;
	public String premiumFlagForSale;
	public String comingSoonDate;
	public Integer subscribers;
	
}
